default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 100
  timeout: 5000

development:
  <<: *default
  database: fox_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: fox_test

production:
  <<: *default
  host: ec2-54-204-3-200.compute-1.amazonaws.com
  database: <%= ENV['FOX_DATABASE_NAME'] %>
  username: <%= ENV['FOX_DATABASE_USER'] %>
  password: <%= ENV['FOX_DATABASE_PASSWORD'] %>